### ISSUE TITLE
Duplicates from multiple issue labels in separate categories

### ISSUE THREAD

**Issue by jonpas** [release-drafter/release-drafter#498]
Our configuration at https://github.com/acemod/ACE3 contains:
```yaml
categories:
  - title: '**IMPROVED:**'
    labels:
      - 'kind/enhancement'
  - title: '**CHANGED:**'
    labels:
      - 'area/compatibility'
```

Having an issue such as https://github.com/acemod/ACE3/pull/7571 labelled with both `kind/enhancement` and `area/compatibility` results in the change becoming drafted twice, once under each category.

Having an option to only pick the first category listed would be very useful for avoiding duplicates like that. I can see why some projects might want it logged in both cases as well.

**Comment by jetersen** [comment]
This is fixed on master by #412

**Comment by jonpas** [comment]
Correct me if I am wrong, but that is not the same issue. Additionally I believe 5.7.0 (which #412 is part of) is already on GitHub Actions, which we are using as `@v5`.

#412 fixes a different issue from this one: Multiple categories being created for same label (eg. one issue having `kind/cleanup` and `area/compatibility` would result in two `CHANGED` categories).

This issue is about multiple labels per **issue** (**not** per **category**) being added to both categories. It is not so much of an issue than an enhancement request for that not to happen.

**Comment by jetersen** [comment]
I have changed @v5 to point to 5.7.0 apparantly it was not updated.

**Comment by jonpas** [comment]
Thank you, I will report back on the result in the coming weeks. I still do not think that is the same issue though.

**Comment by jetersen** [comment]
In the case of adding labels from multiple categories that is the intended effect.

The intention is if you labelled it with two categories it will be added to those two categories.

Jenkins core has a good use case for this: see https://github.com/release-drafter/release-drafter/pull/412#issuecomment-594610087

Remember it is called drafter, it is there to assist you with drafting releases.
You can have a change that could both be breaking and a dependency update and you want it to be added to both section as a place holder for writing a better breaking change or vice versa.

**Comment by jetersen** [comment]
Adding an option seems overkill since in that case you either remove the label or you would simply remove the entry.

**Comment by jonpas** [comment]
Alright, seems like it's a niche use-case. Thank you for your answer!
